version: '3.3'

services:
  database:
    image: postgres:latest
    networks:
      - backend-network
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_PGDATA=${POSTGRES_PGDATA}
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  backend:
    build: .
    ports:
      - '4000:3001'
    environment:
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - DB_SYNCHRONIZE=${DB_SYNCHRONIZE}
      - TELEGRAM_BOT_TOKEN
      - TELEGRAM_BOT_TOKEN_MESSAGES
      - TELEGRAM_CHAT_ID_MESSAGES
      - TELEGRAM_CHAT_ID
      - JWT_SECRET
    networks:
      - backend-network
    restart: unless-stopped

networks:
  backend-network:
    driver: bridge

volumes:
  postgres_data:
